import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { About } from "../components/about";
import Footer from "../components/footer";
import Metadata from "../components/metadata";

const Home: NextPage = () => {
  return (
    <div>
      {/*  <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={"bg-green-500 text-xl"}>
          Welcome to <a href="https://mesh.trade">Mesh mZAR</a>
        </h1>
      </main>

      <footer className={"bg-primary"}>
        <a href="https://mesh.trade" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={""}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
      <About />
      <Metadata />
      <Footer />
    </div>
  );
};

export default Home;
