import type { NextPage } from "next";
import Head from "next/head";
import { About } from "../components/about";
import { Hero } from "../components/hero";
import { Navbar } from "../components/nav-bar";
import { Mesh } from "../components/mesh";
import Footer from "../components/footer";
import Metadata from "../components/metadata";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Mesh mZAR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main>
        <Hero />
        <Mesh />
        <About />
        <Metadata />
        <Footer />
      </main>
    </div>
  );
};

export default Home;
